//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTimeStat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkTimeStat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string cal_btn_change {
            get {
                return ResourceManager.GetString("cal_btn_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete day data.
        /// </summary>
        public static string cal_btn_delete {
            get {
                return ResourceManager.GetString("cal_btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this day&apos;s data? This action is irreversible!.
        /// </summary>
        public static string cal_delete_confirm_dialog_content {
            get {
                return ResourceManager.GetString("cal_delete_confirm_dialog_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion of day data!.
        /// </summary>
        public static string cal_delete_confirm_dialog_header {
            get {
                return ResourceManager.GetString("cal_delete_confirm_dialog_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some values are not correctly filled.
        /// </summary>
        public static string cal_error_incomplete_state_at_save_content {
            get {
                return ResourceManager.GetString("cal_error_incomplete_state_at_save_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data.
        /// </summary>
        public static string cal_error_incomplete_state_at_save_header {
            get {
                return ResourceManager.GetString("cal_error_incomplete_state_at_save_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for this day!.
        /// </summary>
        public static string cal_error_no_data_for_day_content {
            get {
                return ResourceManager.GetString("cal_error_no_data_for_day_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string cal_error_no_data_for_day_header {
            get {
                return ResourceManager.GetString("cal_error_no_data_for_day_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On leave?.
        /// </summary>
        public static string cal_leave_day {
            get {
                return ResourceManager.GetString("cal_leave_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave days left:.
        /// </summary>
        public static string cal_leave_days_left {
            get {
                return ResourceManager.GetString("cal_leave_days_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured hours:.
        /// </summary>
        public static string cal_measured_hours {
            get {
                return ResourceManager.GetString("cal_measured_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On sick pay?.
        /// </summary>
        public static string cal_sick_pay {
            get {
                return ResourceManager.GetString("cal_sick_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked hours:.
        /// </summary>
        public static string cal_worked_hours {
            get {
                return ResourceManager.GetString("cal_worked_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day on customer premises.
        /// </summary>
        public static string enum_customer_desc {
            get {
                return ResourceManager.GetString("enum_customer_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string enum_customer_display {
            get {
                return ResourceManager.GetString("enum_customer_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some out of order work during normal weekdays.
        /// </summary>
        public static string enum_extraordinary_desc {
            get {
                return ResourceManager.GetString("enum_extraordinary_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraordinary.
        /// </summary>
        public static string enum_extraordinary_display {
            get {
                return ResourceManager.GetString("enum_extraordinary_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half day Holiday.
        /// </summary>
        public static string enum_halfday_desc {
            get {
                return ResourceManager.GetString("enum_halfday_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half day.
        /// </summary>
        public static string enum_halfday_display {
            get {
                return ResourceManager.GetString("enum_halfday_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday work.
        /// </summary>
        public static string enum_holiday_desc {
            get {
                return ResourceManager.GetString("enum_holiday_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string enum_holiday_display {
            get {
                return ResourceManager.GetString("enum_holiday_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Office.
        /// </summary>
        public static string enum_home_office_desc {
            get {
                return ResourceManager.GetString("enum_home_office_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Office.
        /// </summary>
        public static string enum_home_office_display {
            get {
                return ResourceManager.GetString("enum_home_office_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various places throughout the day.
        /// </summary>
        public static string enum_mixed_desc {
            get {
                return ResourceManager.GetString("enum_mixed_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various.
        /// </summary>
        public static string enum_mixed_display {
            get {
                return ResourceManager.GetString("enum_mixed_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office day.
        /// </summary>
        public static string enum_office_day_desc {
            get {
                return ResourceManager.GetString("enum_office_day_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string enum_office_day_display {
            get {
                return ResourceManager.GetString("enum_office_day_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work at another location.
        /// </summary>
        public static string enum_other_desc {
            get {
                return ResourceManager.GetString("enum_other_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string enum_other_display {
            get {
                return ResourceManager.GetString("enum_other_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A not usual workday, where only overwork is done (for example a weekend).
        /// </summary>
        public static string enum_overworkday_desc {
            get {
                return ResourceManager.GetString("enum_overworkday_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwork.
        /// </summary>
        public static string enum_overworkday_display {
            get {
                return ResourceManager.GetString("enum_overworkday_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby work.
        /// </summary>
        public static string enum_standby_desc {
            get {
                return ResourceManager.GetString("enum_standby_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby.
        /// </summary>
        public static string enum_standby_display {
            get {
                return ResourceManager.GetString("enum_standby_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal weekday work.
        /// </summary>
        public static string enum_weekday_desc {
            get {
                return ResourceManager.GetString("enum_weekday_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string enum_weekday_display {
            get {
                return ResourceManager.GetString("enum_weekday_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend work.
        /// </summary>
        public static string enum_weekend_desc {
            get {
                return ResourceManager.GetString("enum_weekend_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string enum_weekend_display {
            get {
                return ResourceManager.GetString("enum_weekend_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string lang_hu_HU {
            get {
                return ResourceManager.GetString("lang_hu_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string main_calendar {
            get {
                return ResourceManager.GetString("main_calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s computer usage.
        /// </summary>
        public static string main_daily_usage {
            get {
                return ResourceManager.GetString("main_daily_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set your number of leaves, daily work hours and holiday year start in settings!.
        /// </summary>
        public static string main_error_no_settings_content {
            get {
                return ResourceManager.GetString("main_error_no_settings_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup.
        /// </summary>
        public static string main_error_no_settings_header {
            get {
                return ResourceManager.GetString("main_error_no_settings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string main_exit {
            get {
                return ResourceManager.GetString("main_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string main_settings {
            get {
                return ResourceManager.GetString("main_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string main_statistics {
            get {
                return ResourceManager.GetString("main_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left button work time, Right button menu.
        /// </summary>
        public static string main_tooltip {
            get {
                return ResourceManager.GetString("main_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle size: .
        /// </summary>
        public static string set_bottle_size {
            get {
                return ResourceManager.GetString("set_bottle_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string set_btn_save_and_close {
            get {
                return ResourceManager.GetString("set_btn_save_and_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default place of work:.
        /// </summary>
        public static string set_default_workplace {
            get {
                return ResourceManager.GetString("set_default_workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The place where you work most.
        /// </summary>
        public static string set_default_workplace_tooltip {
            get {
                return ResourceManager.GetString("set_default_workplace_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily work hours: .
        /// </summary>
        public static string set_default_worktime {
            get {
                return ResourceManager.GetString("set_default_worktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of hours you are required to work each workday.
        /// </summary>
        public static string set_default_worktime_tooltip {
            get {
                return ResourceManager.GetString("set_default_worktime_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set your number of leaves and daily work hours!.
        /// </summary>
        public static string set_error_incomplete_setup_content {
            get {
                return ResourceManager.GetString("set_error_incomplete_setup_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete setup.
        /// </summary>
        public static string set_error_incomplete_setup_header {
            get {
                return ResourceManager.GetString("set_error_incomplete_setup_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is lunchtime worktime?.
        /// </summary>
        public static string set_is_lunchtime_worktime {
            get {
                return ResourceManager.GetString("set_is_lunchtime_worktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether your lunchtime is counted as part of your worktime.
        /// </summary>
        public static string set_is_lunchtime_worktime_tooltip {
            get {
                return ResourceManager.GetString("set_is_lunchtime_worktime_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language:.
        /// </summary>
        public static string set_language {
            get {
                return ResourceManager.GetString("set_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the UI. You MUST restart the app for it to take full effect!.
        /// </summary>
        public static string set_language_tooltip {
            get {
                return ResourceManager.GetString("set_language_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave days in a year:.
        /// </summary>
        public static string set_leave_days_in_year {
            get {
                return ResourceManager.GetString("set_leave_days_in_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of days you have to go on vacation.
        /// </summary>
        public static string set_leave_days_in_year_tooltip {
            get {
                return ResourceManager.GetString("set_leave_days_in_year_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity watcher resolution:.
        /// </summary>
        public static string set_usagewatcher_resolution {
            get {
                return ResourceManager.GetString("set_usagewatcher_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of minutes counted as usage after using the keyboard or mouse.
        /// </summary>
        public static string set_usagewatcher_resolution_tooltip {
            get {
                return ResourceManager.GetString("set_usagewatcher_resolution_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of year for holidays:.
        /// </summary>
        public static string set_year_start {
            get {
                return ResourceManager.GetString("set_year_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date on which your vacation days are reset.
        /// </summary>
        public static string set_year_start_tooltip {
            get {
                return ResourceManager.GetString("set_year_start_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks:.
        /// </summary>
        public static string stat_data_breaks {
            get {
                return ResourceManager.GetString("stat_data_breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usageflow:.
        /// </summary>
        public static string stat_data_flow {
            get {
                return ResourceManager.GetString("stat_data_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference:.
        /// </summary>
        public static string stat_diff_in_hours {
            get {
                return ResourceManager.GetString("stat_diff_in_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last day:.
        /// </summary>
        public static string stat_last_day {
            get {
                return ResourceManager.GetString("stat_last_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month:.
        /// </summary>
        public static string stat_last_month {
            get {
                return ResourceManager.GetString("stat_last_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured hours:.
        /// </summary>
        public static string stat_measured_hours {
            get {
                return ResourceManager.GetString("stat_measured_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed hours:.
        /// </summary>
        public static string stat_needed_hours {
            get {
                return ResourceManager.GetString("stat_needed_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string stat_overview_tab_name {
            get {
                return ResourceManager.GetString("stat_overview_tab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month:.
        /// </summary>
        public static string stat_this_month {
            get {
                return ResourceManager.GetString("stat_this_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today:.
        /// </summary>
        public static string stat_today {
            get {
                return ResourceManager.GetString("stat_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage data.
        /// </summary>
        public static string stat_usage_tab_name {
            get {
                return ResourceManager.GetString("stat_usage_tab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked hours:.
        /// </summary>
        public static string stat_worked_hours {
            get {
                return ResourceManager.GetString("stat_worked_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string u_btn_cancel {
            get {
                return ResourceManager.GetString("u_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string u_btn_close {
            get {
                return ResourceManager.GetString("u_btn_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string u_btn_save {
            get {
                return ResourceManager.GetString("u_btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string u_hour {
            get {
                return ResourceManager.GetString("u_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch break:.
        /// </summary>
        public static string u_lunch_break_length {
            get {
                return ResourceManager.GetString("u_lunch_break_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string u_minute {
            get {
                return ResourceManager.GetString("u_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other break:.
        /// </summary>
        public static string u_other_break_length {
            get {
                return ResourceManager.GetString("u_other_break_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwork:.
        /// </summary>
        public static string u_overwork_length {
            get {
                return ResourceManager.GetString("u_overwork_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time:.
        /// </summary>
        public static string u_work_end_time {
            get {
                return ResourceManager.GetString("u_work_end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        public static string u_work_start_time {
            get {
                return ResourceManager.GetString("u_work_start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday type:.
        /// </summary>
        public static string u_workday_type {
            get {
                return ResourceManager.GetString("u_workday_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of work:.
        /// </summary>
        public static string u_workplace {
            get {
                return ResourceManager.GetString("u_workplace", resourceCulture);
            }
        }
    }
}
